module corbaAccount {	
	interface date {
		attribute long day;
		attribute long month;
		attribute long year;
		
		string toString();
	};
	
	enum operationType {ADD, WITHDRAW};
	
	interface Operation {
		attribute operationType type;
		attribute float amount;
	};

	typedef sequence<Operation> accountOperationsType;

	interface Account {
		attribute long accountId;
		attribute string name;
		attribute string surname;
		attribute date dateAccountCreated;
		attribute float balance;
		attribute accountOperationsType accountOperations;

		string details();
		void addOperation(in Operation op);
		string toString();
	};
};
